// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/haberdasher/service.proto

package haberdasher

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Color int32

const (
	Color_RED   Color = 0
	Color_GREEN Color = 1
	Color_BLUE  Color = 2
)

var Color_name = map[int32]string{
	0: "RED",
	1: "GREEN",
	2: "BLUE",
}

var Color_value = map[string]int32{
	"RED":   0,
	"GREEN": 1,
	"BLUE":  2,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12bf52606c1675ec, []int{0}
}

// Size of a Hat, in inches.
type Size struct {
	Inches               int32    `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_12bf52606c1675ec, []int{0}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

// A Hat is a piece of headwear made by a Haberdasher.
type Hat struct {
	Inches               int32    `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	Color                Color    `protobuf:"varint,2,opt,name=color,proto3,enum=disc.twirpexample.haberdasher.Color" json:"color,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_12bf52606c1675ec, []int{1}
}

func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (m *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(m, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

func (m *Hat) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_RED
}

func (m *Hat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("disc.twirpexample.haberdasher.Color", Color_name, Color_value)
	proto.RegisterType((*Size)(nil), "disc.twirpexample.haberdasher.Size")
	proto.RegisterType((*Hat)(nil), "disc.twirpexample.haberdasher.Hat")
}

func init() { proto.RegisterFile("rpc/haberdasher/service.proto", fileDescriptor_12bf52606c1675ec) }

var fileDescriptor_12bf52606c1675ec = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x2a, 0x48, 0xd6,
	0xcf, 0x48, 0x4c, 0x4a, 0x2d, 0x4a, 0x49, 0x2c, 0xce, 0x48, 0x2d, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4d, 0xc9, 0x2c, 0x4e, 0xd6,
	0x2b, 0x29, 0xcf, 0x2c, 0x2a, 0x48, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x43, 0x52, 0xac,
	0x24, 0xc7, 0xc5, 0x12, 0x9c, 0x59, 0x95, 0x2a, 0x24, 0xc6, 0xc5, 0x96, 0x99, 0x97, 0x9c, 0x91,
	0x5a, 0x2c, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x29, 0xe5, 0x72, 0x31, 0x7b, 0x24,
	0x96, 0xe0, 0x92, 0x16, 0xb2, 0xe2, 0x62, 0x4d, 0xce, 0xcf, 0xc9, 0x2f, 0x92, 0x60, 0x52, 0x60,
	0xd4, 0xe0, 0x33, 0x52, 0xd1, 0xc3, 0x6b, 0x9b, 0x9e, 0x33, 0x48, 0x6d, 0x10, 0x44, 0x8b, 0x90,
	0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad,
	0xa5, 0xca, 0xc5, 0x0a, 0x56, 0x23, 0xc4, 0xce, 0xc5, 0x1c, 0xe4, 0xea, 0x22, 0xc0, 0x20, 0xc4,
	0xc9, 0xc5, 0xea, 0x1e, 0xe4, 0xea, 0xea, 0x27, 0xc0, 0x28, 0xc4, 0xc1, 0xc5, 0xe2, 0xe4, 0x13,
	0xea, 0x2a, 0xc0, 0x64, 0x94, 0xc8, 0xc5, 0xed, 0x81, 0x30, 0x56, 0x28, 0x88, 0x8b, 0xdd, 0x37,
	0x31, 0x3b, 0x15, 0xe4, 0x50, 0x65, 0x02, 0x2e, 0x00, 0x79, 0x56, 0x4a, 0x89, 0x80, 0x22, 0x8f,
	0xc4, 0x12, 0x27, 0xde, 0x28, 0x6e, 0x24, 0xa1, 0x24, 0x36, 0x70, 0x68, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x05, 0x87, 0x54, 0xc5, 0x6e, 0x01, 0x00, 0x00,
}
